const StoriesViewerSheetTypes = {
    NO_VIEWERSHEET: "NO_VIEWERSHEET",
    PAGE_STORY_VIEWERSHEET: "PAGE_STORY_VIEWERSHEET",
    SELF_STORY_VIEWERSHEET: "SELF_STORY_VIEWERSHEET",
};

export default StoriesViewerSheetTypes;