__d(
  "CometKeys",
  ["Locale"],
  function (a, b, c, d, e, f, g) {
    "use strict";
    a = Object.freeze({
      AREA_NAV: "f6",
      COMMA: ",",
      DEL: "delete",
      DELETE: "backspace",
      DOT: ".",
      DOWN: "arrowdown",
      END: "end",
      ENTER: "enter",
      EQUAL: "=",
      ESCAPE: "escape",
      HOME: "home",
      LEFT: d("Locale").isRTL() ? "arrowright" : "arrowleft",
      LEFT_SQUARE_BRACKET: "[",
      MINUS: "-",
      NEXT: d("Locale").isRTL() ? "arrowleft" : "arrowright",
      PAGE_DOWN: "pagedown",
      PAGE_UP: "pageup",
      PREVIOUS: d("Locale").isRTL() ? "arrowright" : "arrowleft",
      QUESTION: "?",
      RIGHT: d("Locale").isRTL() ? "arrowleft" : "arrowright",
      RIGHT_SQUARE_BRACKET: "]",
      SEMI_COLON: ";",
      SLASH: "/",
      SPACE: " ",
      TAB: "tab",
      UP: "arrowup",
      F1: "f1",
      F2: "f2",
      F3: "f3",
      F4: "f4",
      F5: "f5",
      F6: "f6",
      F7: "f7",
      F8: "f8",
      F9: "f9",
      F10: "f10",
      F11: "f11",
      F12: "f12",
      ONE: "1",
      TWO: "2",
      THREE: "3",
      FOUR: "4",
      FIVE: "5",
      SIX: "6",
      SEVEN: "7",
      EIGHT: "8",
      NINE: "9",
      ZERO: "0",
      A: "a",
      B: "b",
      C: "c",
      D: "d",
      E: "e",
      F: "f",
      G: "g",
      H: "h",
      I: "i",
      J: "j",
      K: "k",
      L: "l",
      M: "m",
      N: "n",
      O: "o",
      P: "p",
      Q: "q",
      R: "r",
      S: "s",
      T: "t",
      U: "u",
      V: "v",
      W: "w",
      X: "x",
      Y: "y",
      Z: "z",
    });
    b = a;
    g["default"] = b;
  },
  98
);

import { Locale } from "Locale";

const CometKeys = Object.freeze({
  AREA_NAV: "f6",
  COMMA: ",",
  DEL: "delete",
  DELETE: "backspace",
  DOT: ".",
  DOWN: "arrowdown",
  END: "end",
  ENTER: "enter",
  EQUAL: "=",
  ESCAPE: "escape",
  HOME: "home",
  LEFT: Locale.isRTL() ? "arrowright" : "arrowleft",
  LEFT_SQUARE_BRACKET: "[",
  MINUS: "-",
  NEXT: Locale.isRTL() ? "arrowleft" : "arrowright",
  PAGE_DOWN: "pagedown",
  PAGE_UP: "pageup",
  PREVIOUS: Locale.isRTL() ? "arrowright" : "arrowleft",
  QUESTION: "?",
  RIGHT: Locale.isRTL() ? "arrowleft" : "arrowright",
  RIGHT_SQUARE_BRACKET: "]",
  SEMI_COLON: ";",
  SLASH: "/",
  SPACE: " ",
  TAB: "tab",
  UP: "arrowup",
  F1: "f1",
  F2: "f2",
  F3: "f3",
  F4: "f4",
  F5: "f5",
  F6: "f6",
  F7: "f7",
  F8: "f8",
  F9: "f9",
  F10: "f10",
  F11: "f11",
  F12: "f12",
  ONE: "1",
  TWO: "2",
  THREE: "3",
  FOUR: "4",
  FIVE: "5",
  SIX: "6",
  SEVEN: "7",
  EIGHT: "8",
  NINE: "9",
  ZERO: "0",
  A: "a",
  B: "b",
  C: "c",
  D: "d",
  E: "e",
  F: "f",
  G: "g",
  H: "h",
  I: "i",
  J: "j",
  K: "k",
  L: "l",
  M: "m",
  N: "n",
  O: "o",
  P: "p",
  Q: "q",
  R: "r",
  S: "s",
  T: "t",
  U: "u",
  V: "v",
  W: "w",
  X: "x",
  Y: "y",
  Z: "z",
});

export default CometKeys;
