__d(
  "LSMessageReplySourceTypeV2",
  [],
  function (a, b, c, d, e, f) {
    a = Object.freeze({
      NONE: 0,
      MESSAGE: 1,
      STORY: 2,
      FORWARD: 3,
      FB_STORY_SHARE: 4,
      IG_STORY_SHARE: 5,
      STORY_BASE64_ENCODED: 6,
      LIGHTWEIGHT_STATUS: 7,
      CLOSE_FRIENDS: 8,
      XMA: 9,
      IG_NOTE: 10,
      CLOSE_FRIENDS_NOTE_REPLY: 11,
      LIGHTWEIGHT_STATUS_REACTION: 12,
      FB_FEED_POST: 13,
      HIGHLIGHTS_TAB_POST_REPLY: 14,
      HIGHLIGHTS_TAB_LOCAL_EVENT_REPLY: 15,
      SHARED_ALBUM: 16,
      AVATAR_DETAIL: 17,
      NOTE_REPLY_ARMADILLO: 18,
      HIGHLIGHTS_TAB_CARDS_FOR_MOM: 19,
    });
    f["default"] = a;
  },
  66
);

const LSMessageReplySourceTypeV2 = Object.freeze({
  NONE: 0,
  MESSAGE: 1,
  STORY: 2,
  FORWARD: 3,
  FB_STORY_SHARE: 4,
  IG_STORY_SHARE: 5,
  STORY_BASE64_ENCODED: 6,
  LIGHTWEIGHT_STATUS: 7,
  CLOSE_FRIENDS: 8,
  XMA: 9,
  IG_NOTE: 10,
  CLOSE_FRIENDS_NOTE_REPLY: 11,
  LIGHTWEIGHT_STATUS_REACTION: 12,
  FB_FEED_POST: 13,
  HIGHLIGHTS_TAB_POST_REPLY: 14,
  HIGHLIGHTS_TAB_LOCAL_EVENT_REPLY: 15,
  SHARED_ALBUM: 16,
  AVATAR_DETAIL: 17,
  NOTE_REPLY_ARMADILLO: 18,
  HIGHLIGHTS_TAB_CARDS_FOR_MOM: 19,
});

export default LSMessageReplySourceTypeV2;
