__d(
  "MWPAudioPlayerSharedStyles",
  [],
  function (a, b, c, d, e, f, g) {
    "use strict";
    a = {
      bar: {
        backgroundColor: "x14hiurz",
        borderTopStartRadius: "x1inr27j",
        borderTopEndRadius: "x1vcqv9c",
        borderBottomEndRadius: "xfrm7hi",
        borderBottomStartRadius: "xpbad92",
        boxShadow: "x49dmcg",
        height: "xn3w4p2",
        position: "x10l6tqk",
        top: "xwa60dl",
        transform: "x1cb1t30",
        width: "x51ohtg",
        zIndex: "x1vjfegm",
        $$css: !0,
      },
      common: {
        alignItems: "x6s0dn4",
        alignSelf: "xkh2ocl",
        backgroundAttachment: "x1nr1p0w",
        borderTopStartRadius: "x1tlxs6b",
        borderTopEndRadius: "x1g8br2z",
        borderBottomEndRadius: "x1gn5b1j",
        borderBottomStartRadius: "x230xth",
        display: "x78zum5",
        flexGrow: "x1iyjqo2",
        justifyContent: "x1qughib",
        outline: "x1k4qllp",
        $$css: !0,
      },
      commonIncoming: { backgroundColor: "x1xr0vuk", $$css: !0 },
      commonOutgoing: { backgroundColor: "x11jlvup", $$css: !0 },
      commonOutgoingReply: { backgroundImage: "xl54vp5", $$css: !0 },
      commonReply: { outline: "x1ucz5p", $$css: !0 },
      container: {
        alignItems: "x6s0dn4",
        display: "x78zum5",
        flexGrow: "x1iyjqo2",
        justifyContent: "x1qughib",
        overflowX: "x6ikm8r",
        overflowY: "x10wlt62",
        position: "x1n2onr6",
        $$css: !0,
      },
      highlight: {
        height: "x5yr21d",
        position: "x10l6tqk",
        start: "x17qophe",
        left: null,
        right: null,
        top: "x13vifvy",
        width: "xh8yej3",
        $$css: !0,
      },
      incomingWaveFormStyle: { fill: "x1f9y4dh", $$css: !0 },
      mask: {
        height: "x5yr21d",
        position: "x10l6tqk",
        width: "xh8yej3",
        $$css: !0,
      },
      outgoingWaveFormStyle: { fill: "xe3v8dz", $$css: !0 },
      playbackButtonContainer: {
        marginStart: "x1mnrxsn",
        marginLeft: null,
        marginRight: null,
        marginEnd: "x1w0mnb",
        $$css: !0,
      },
      pressable: {
        alignItems: "x6s0dn4",
        backgroundColor: "x14hiurz",
        borderTopStartRadius: "x14yjl9h",
        borderTopEndRadius: "xudhj91",
        borderBottomEndRadius: "x18nykt9",
        borderBottomStartRadius: "xww2gxu",
        display: "x78zum5",
        height: "xxk0z11",
        justifyContent: "xl56j7k",
        minWidth: "xnei2rj",
        $$css: !0,
      },
      rightSideBottom: {
        backgroundColor: "x14hiurz",
        borderTopStartRadius: "xfj52jq",
        borderTopEndRadius: "xykzs3s",
        borderBottomEndRadius: "x17xv1ja",
        borderBottomStartRadius: "x1mvicbb",
        $$css: !0,
      },
      rightSideImprove: {
        marginStart: "x16n37ib",
        marginLeft: null,
        marginRight: null,
        marginEnd: "xq8finb",
        width: "x1691je0",
        $$css: !0,
      },
      rightSideMargin: { marginTop: "x1gslohp", $$css: !0 },
      rightSideTop: {
        alignItems: "x6s0dn4",
        color: "x1a3ma36",
        display: "x78zum5",
        fontSize: "x1nxh6w3",
        fontWeight: "x1s688f",
        height: "xi0exxh",
        justifyContent: "xl56j7k",
        marginStart: "x1mnrxsn",
        marginLeft: null,
        marginRight: null,
        marginEnd: "x1w0mnb",
        position: "x1n2onr6",
        userSelect: "x87ps6o",
        width: "x1r9kitl",
        $$css: !0,
      },
      scrubber: {
        alignItems: "x6s0dn4",
        display: "x78zum5",
        height: "x5yr21d",
        position: "x1n2onr6",
        width: "xh8yej3",
        zIndex: "x1vjfegm",
        $$css: !0,
      },
      transparent: {
        height: "x5yr21d",
        overflowX: "x6ikm8r",
        overflowY: "x10wlt62",
        paddingTop: "xexx8yu",
        paddingEnd: "x4uap5",
        paddingBottom: "x18d9i69",
        paddingStart: "xkhd6sd",
        position: "x1n2onr6",
        "::after_borderTopColor": "x14617ij",
        "::after_borderEndColor": "x1b5s2of",
        "::after_borderBottomColor": "xv84cap",
        "::after_borderStartColor": "x15ngzmr",
        "::after_borderTopStartRadius": "xwuuf8d",
        "::after_borderTopEndRadius": "xpd6q6o",
        "::after_borderBottomEndRadius": "x1n6g0fn",
        "::after_borderBottomStartRadius": "xu4xob7",
        "::after_borderTopStyle": "xynf4tj",
        "::after_borderEndStyle": "xdspwft",
        "::after_borderBottomStyle": "x1r9ni5o",
        "::after_borderStartStyle": "x1d52zm6",
        "::after_borderTopWidth": "x1gnji40",
        "::after_borderEndWidth": "xymhjbi",
        "::after_borderBottomWidth": "x1ekxc0f",
        "::after_borderStartWidth": "x5arhyh",
        "::after_bottom": "x14apmda",
        "::after_content": "x1s928wv",
        "::after_display": "xhkezso",
        "::after_end": "xhyvd7x",
        "::after_left": null,
        "::after_right": null,
        "::after_pointerEvents": "x2q1x1w",
        "::after_position": "x1j6awrg",
        "::after_start": "x1aneyt",
        "::after_top": "xso615a",
        $$css: !0,
      },
      transparentBar: {
        backgroundColor: "xjbqb8w",
        borderTopStartRadius: "x1inr27j",
        borderTopEndRadius: "x1vcqv9c",
        borderBottomEndRadius: "xfrm7hi",
        borderBottomStartRadius: "xpbad92",
        boxShadow: "x49dmcg",
        height: "xn3w4p2",
        position: "x10l6tqk",
        top: "xwa60dl",
        transform: "x1cb1t30",
        width: "x51ohtg",
        zIndex: "x1vjfegm",
        $$css: !0,
      },
      waveform: {
        height: "xn3w4p2",
        position: "x1n2onr6",
        width: "xh8yej3",
        $$css: !0,
      },
    };
    g.styles = a;
  },
  98
);

interface Style {
  [key: string]: string | null;
}

interface MWPAudioPlayerSharedStyles {
  bar: Style;
  common: Style;
  commonIncoming: Style;
  commonOutgoing: Style;
  commonOutgoingReply: Style;
  commonReply: Style;
  container: Style;
  highlight: Style;
  incomingWaveFormStyle: Style;
  mask: Style;
  outgoingWaveFormStyle: Style;
  playbackButtonContainer: Style;
  pressable: Style;
  rightSideBottom: Style;
  rightSideImprove: Style;
  rightSideMargin: Style;
  rightSideTop: Style;
  scrubber: Style;
  transparent: Style;
  transparentBar: Style;
  waveform: Style;
}

const styles: MWPAudioPlayerSharedStyles = {
  bar: {
    backgroundColor: "x14hiurz",
    borderTopStartRadius: "x1inr27j",
    borderTopEndRadius: "x1vcqv9c",
    borderBottomEndRadius: "xfrm7hi",
    borderBottomStartRadius: "xpbad92",
    boxShadow: "x49dmcg",
    height: "xn3w4p2",
    position: "x10l6tqk",
    top: "xwa60dl",
    transform: "x1cb1t30",
    width: "x51ohtg",
    zIndex: "x1vjfegm",
    $$css: true,
  },
  common: {
    alignItems: "x6s0dn4",
    alignSelf: "xkh2ocl",
    backgroundAttachment: "x1nr1p0w",
    borderTopStartRadius: "x1tlxs6b",
    borderTopEndRadius: "x1g8br2z",
    borderBottomEndRadius: "x1gn5b1j",
    borderBottomStartRadius: "x230xth",
    display: "x78zum5",
    flexGrow: "x1iyjqo2",
    justifyContent: "x1qughib",
    outline: "x1k4qllp",
    $$css: true,
  },
  commonIncoming: { backgroundColor: "x1xr0vuk", $$css: true },
  commonOutgoing: { backgroundColor: "x11jlvup", $$css: true },
  commonOutgoingReply: { backgroundImage: "xl54vp5", $$css: true },
  commonReply: { outline: "x1ucz5p", $$css: true },
  container: {
    alignItems: "x6s0dn4",
    display: "x78zum5",
    flexGrow: "x1iyjqo2",
    justifyContent: "x1qughib",
    overflowX: "x6ikm8r",
    overflowY: "x10wlt62",
    position: "x1n2onr6",
    $$css: true,
  },
  highlight: {
    height: "x5yr21d",
    position: "x10l6tqk",
    start: "x17qophe",
    left: null,
    right: null,
    top: "x13vifvy",
    width: "xh8yej3",
    $$css: true,
  },
  incomingWaveFormStyle: { fill: "x1f9y4dh", $$css: true },
  mask: {
    height: "x5yr21d",
    position: "x10l6tqk",
    width: "xh8yej3",
    $$css: true,
  },
  outgoingWaveFormStyle: { fill: "xe3v8dz", $$css: true },
  playbackButtonContainer: {
    marginStart: "x1mnrxsn",
    marginLeft: null,
    marginRight: null,
    marginEnd: "x1w0mnb",
    $$css: true,
  },
  pressable: {
    alignItems: "x6s0dn4",
    backgroundColor: "x14hiurz",
    borderTopStartRadius: "x14yjl9h",
    borderTopEndRadius: "xudhj91",
    borderBottomEndRadius: "x18nykt9",
    borderBottomStartRadius: "xww2gxu",
    display: "x78zum5",
    height: "xxk0z11",
    justifyContent: "xl56j7k",
    minWidth: "xnei2rj",
    $$css: true,
  },
  rightSideBottom: {
    backgroundColor: "x14hiurz",
    borderTopStartRadius: "xfj52jq",
    borderTopEndRadius: "xykzs3s",
    borderBottomEndRadius: "x17xv1ja",
    borderBottomStartRadius: "x1mvicbb",
    $$css: true,
  },
  rightSideImprove: {
    marginStart: "x16n37ib",
    marginLeft: null,
    marginRight: null,
    marginEnd: "xq8finb",
    width: "x1691je0",
    $$css: true,
  },
  rightSideMargin: { marginTop: "x1gslohp", $$css: true },
  rightSideTop: {
    alignItems: "x6s0dn4",
    color: "x1a3ma36",
    display: "x78zum5",
    fontSize: "x1nxh6w3",
    fontWeight: "x1s688f",
    height: "xi0exxh",
    justifyContent: "xl56j7k",
    marginStart: "x1mnrxsn",
    marginLeft: null,
    marginRight: null,
    marginEnd: "x1w0mnb",
    position: "x1n2onr6",
    userSelect: "x87ps6o",
    width: "x1r9kitl",
    $$css: true,
  },
  scrubber: {
    alignItems: "x6s0dn4",
    display: "x78zum5",
    height: "x5yr21d",
    position: "x1n2onr6",
    width: "xh8yej3",
    zIndex: "x1vjfegm",
    $$css: true,
  },
  transparent: {
    height: "x5yr21d",
    overflowX: "x6ikm8r",
    overflowY: "x10wlt62",
    paddingTop: "xexx8yu",
    paddingEnd: "x4uap5",
    paddingBottom: "x18d9i69",
    paddingStart: "xkhd6sd",
    position: "x1n2onr6",
    "::after_borderTopColor": "x14617ij",
    "::after_borderEndColor": "x1b5s2of",
    "::after_borderBottomColor": "xv84cap",
    "::after_borderStartColor": "x15ngzmr",
    "::after_borderTopStartRadius": "xwuuf8d",
    "::after_borderTopEndRadius": "xpd6q6o",
    "::after_borderBottomEndRadius": "x1n6g0fn",
    "::after_borderBottomStartRadius": "xu4xob7",
    "::after_borderTopStyle": "xynf4tj",
    "::after_borderEndStyle": "xdspwft",
    "::after_borderBottomStyle": "x1r9ni5o",
    "::after_borderStartStyle": "x1d52zm6",
    "::after_borderTopWidth": "x1gnji40",
    "::after_borderEndWidth": "xymhjbi",
    "::after_borderBottomWidth": "x1ekxc0f",
    "::after_borderStartWidth": "x5arhyh",
    "::after_bottom": "x14apmda",
    "::after_content": "x1s928wv",
    "::after_display": "xhkezso",
    "::after_end": "xhyvd7x",
    "::after_left": null,
    "::after_right": null,
    "::after_pointerEvents": "x2q1x1w",
    "::after_position": "x1j6awrg",
    "::after_start": "x1aneyt",
    "::after_top": "xso615a",
    $$css: true,
  },
  transparentBar: {
    backgroundColor: "xjbqb8w",
    borderTopStartRadius: "x1inr27j",
    borderTopEndRadius: "x1vcqv9c",
    borderBottomEndRadius: "xfrm7hi",
    borderBottomStartRadius: "xpbad92",
    boxShadow: "x49dmcg",
    height: "xn3w4p2",
    position: "x10l6tqk",
    top: "xwa60dl",
    transform: "x1cb1t30",
    width: "x51ohtg",
    zIndex: "x1vjfegm",
    $$css: true,
  },
  waveform: {
    height: "xn3w4p2",
    position: "x1n2onr6",
    width: "xh8yej3",
    $$css: true,
  },
};

export { MWPAudioPlayerSharedStyles };
