export const routes = {
    cms: "cms",
    activityLog: "activityLog",
    add: "add",
    assets: "assets",
    cmsHome: (0, r.Oe)("cms", "cms"),
    cmsItems: "cms/items",
    cmsItemEdit: "cms/item/edit",
    cmsCollectionEditPreview: "cms/collection/edit/preview",
    cmsCollectionEdit: "cms/collection/edit",
    cmsCsv: "cms/csv",
    commerce: (0, r.Oe)("commerce", "cms"),
    commerceGettingStarted: (0, r.Oe)("commerce", "gettingStarted"),
    commerceDiscounts: (0, r.Oe)("commerce", "discounts"),
    commerceDiscountsEdit: (0, r.Oe)("commerce", "discounts/edit"),
    commerceOrders: (0, r.Oe)("commerce", "orders"),
    commerceSubscriptions: (0, r.Oe)("commerce", "subscriptions"),
    settingsCommerce: "settings/commerce",
    settingsEmail: "settings/email",
    flows: "flows",
    flowsFlows: "flows/flows",
    flowsFlowsAuthoring: "flows/flows/authoring",
    flowsValues: "flows/values",
    navigator: "navigator",
    pages: "pages",
    pageSettings: "pageSettings",
    apps: "apps",
    appsApp: "apps/app",
    siteSettings: "siteSettings",
    generalSettings: "generalSettings",
    interfaceSettings: "interfaceSettings",
    symbols: "symbols",
    tutorials: "tutorials",
    users: "users",
    usersSetup: "users/setup",
    usersData: "users/data",
    usersDataEdit: "users/data/edit",
    usersSchema: "users/schema",
    usersSchemaPreview: "users/schema/preview",
    usersGroups: "users/groups",
    usersGroupsEdit: "users/groups/edit",
    vz: a.vz,
    Gm: a.Gm,
    versions: "versions",
    auditor: "auditor",
    addLayout: "addLayout",
    help: "help",
    styles: "styles",
};